function showFolder() {


    var $ = go.GraphObject.make;

    var myDiagram =
        $(go.Diagram, "myDiagramDiv", {
            initialContentAlignment: go.Spot.Center, // center Diagram contents
            "undoManager.isEnabled": true, // enable Ctrl-Z to undo and Ctrl-Y to redo
            layout: $(go.TreeLayout, // specify a Diagram.layout that arranges trees
                { angle: 0, layerSpacing: 35 })
        });

    // the template we defined earlier
    myDiagram.nodeTemplate =
        $(go.Node, "Horizontal", { background: "#44CCFF" },
            $(go.TextBlock, "Default Text", { margin: 12, stroke: "white", font: "bold 16px sans-serif" },
                new go.Binding("text", "name"))
        );


    // define a Link template that routes orthogonally, with no arrowhead
    myDiagram.linkTemplate =
        $(go.Link, { routing: go.Link.Orthogonal, corner: 5 },
            $(go.Shape, "RoundedRectangle", { strokeWidth: 3, stroke: "#555" })); // the link shape

    var model = $(go.TreeModel);
    model.nodeDataArray = [
        { key: "1", name: "QBurst Portal"},
        { key: "2", parent: "1", name: "js"},
        { key: "3", parent: "1", name: "src"},
        { key: "4", parent: "1", name: "styles"},
        { key: "5", parent: "3", name: "lib" },
        { key: "6", parent: "3", name: "qburst"},
        { key: "7", parent: "6", name: "fonts" },
        { key: "8", parent: "6", name: "media"},
        { key: "9", parent: "6", name: "views"},
        { key: "10", parent: "8", name: "fonts"},
        { key: "11", parent: "8", name: "images"},
        { key: "12", parent: "8", name: "js"},
        { key: "13", parent: "8", name: "styles"},
        { key: "14", parent: "8", name: "resources"},
        { key: "15", parent: "10", name: "Avenir"},
        { key: "16", parent: "10", name: "homefonts"},
        { key: "17", parent: "10", name: "kelsonfonts"},
        { key: "18", parent: "10", name: "OpenSans"},
        { key: "19", parent: "10", name: "oxygen"},
        { key: "20", parent: "10", name: "ptSans"},
        { key: "21", parent: "10", name: "qburstFonts"},
        { key: "22", parent: "10", name: "Universe"},
        { key: "23", parent: "10", name: "Universe_cons_bold"},
        { key: "24", parent: "11", name: "common"},
        { key: "25", parent: "11", name: "company"},
        { key: "26", parent: "11", name: "emailTemplate" },
        { key: "27", parent: "11", name: "Home"},
        { key: "28", parent: "11", name: "industries"},
        { key: "29", parent: "11", name: "clientTestimonails"},
        { key: "30", parent: "11", name: "lyteBox" },
        { key: "31", parent: "11", name: "responsive"},
        { key: "32", parent: "25", name: "companyLanding"},
        { key: "33", parent: "25", name: "careers"},
        { key: "34", parent: "25", name: "contact" },
        { key: "35", parent: "31", name: "appoach"},
        { key: "36", parent: "31", name: "clients"},
        { key: "37", parent: "31", name: "clientTestimonails"},
        { key: "38", parent: "31", name: "common"},
        { key: "39", parent: "31", name: "company"},
        { key: "40", parent: "31", name: "industries"},
        { key: "41", parent: "31", name: "products"},
        { key: "42", parent: "31", name: "services"},
        { key: "43", parent: "31", name: "solutions"},
        { key: "44", parent: "35", name: "delivery" },
        { key: "45", parent: "35", name: "design" },
        { key: "46", parent: "35", name: "testing"},
        { key: "47", parent: "39", name: "aboutUs" },
        { key: "48", parent: "39", name: "contact"},
        { key: "49", parent: "39", name: "careers" },
        { key: "50", parent: "39", name: "partners"},
        { key: "51", parent: "47", name: "clientTele"},
        { key: "52", parent: "47", name: "management"},
        { key: "53", parent: "47", name: "techno" },
        { key: "54", parent: "40", name: "education"},
        { key: "55", parent: "40", name: "engineering"},
        { key: "56", parent: "40", name: "financial"},
        { key: "57", parent: "40", name: "health" },
        { key: "58", parent: "40", name: "retail"},
        { key: "59", parent: "41", name: "context" },
        { key: "60", parent: "41", name: "crickees"},
        { key: "61", parent: "41", name: "Iot" },
        { key: "62", parent: "41", name: "kever"},
        { key: "63", parent: "41", name: "Exsitu" },
        { key: "64", parent: "41", name: "openSource"},
        { key: "65", parent: "41", name: "inspktr"},
        { key: "66", parent: "41", name: "PenQ" },
        { key: "67", parent: "41", name: "tezzle" },
        { key: "68", parent: "41", name: "webwatch"},
        { key: "69", parent: "41", name: "quickpicks" },
        { key: "70", parent: "41", name: "qBecon" },
        { key: "71", parent: "42", name: "analytics"},
        { key: "72", parent: "42", name: "cloud"},
        { key: "73", parent: "42", name: "design"},
        { key: "74", parent: "42", name: "devops" },
        { key: "75", parent: "42", name: "mobile"},
        { key: "76", parent: "42", name: "social" },
        { key: "78", parent: "42", name: "testing"},
        { key: "79", parent: "42", name: "web" },
        { key: "80", parent: "71", name: "BDanalytics"},
        { key: "81", parent: "71", name: "businessInt" },
        { key: "82", parent: "71", name: "dataVisualisation"},
        { key: "83", parent: "71", name: "MachineLearning"},
        { key: "84", parent: "80", name: "ColumnarDB" },
        { key: "85", parent: "80", name: "GraphDB" },
        { key: "86", parent: "80", name: "documentDB"},
        { key: "87", parent: "80", name: "KeyValue" },
        { key: "88", parent: "72", name: "cloudSoln" },
        { key: "89", parent: "88", name: "AWS" },
        { key: "90", parent: "88", name: "Azure" },
        { key: "91", parent: "88", name: "GoogleAppEngine"},
        { key: "92", parent: "88", name: "privatecloud"},
        { key: "93", parent: "88", name: "salesforce"},
        { key: "94", parent: "73", name: "ia" },
        { key: "95", parent: "73", name: "portfolio"},
        { key: "96", parent: "73", name: "rwd" },
        { key: "98", parent: "73", name: "uxd"},
        { key: "99", parent: "75", name: "iphone" },
        { key: "100", parent: "75", name: "android"},
        { key: "101", parent: "75", name: "crossplatform" },
        { key: "102", parent: "75", name: "pwa"},
        { key: "103", parent: "75", name: "windows"},
        { key: "104", parent: "76", name: "competitive" },
        { key: "105", parent: "76", name: "socialMedia" },
        { key: "106", parent: "78", name: "performance"},
        { key: "107", parent: "78", name: "security" },
        { key: "108", parent: "72", name: "cloudSoln" },
        { key: "109", parent: "79", name: "blockchain" },
        { key: "110", parent: "79", name: "cms"},
        { key: "111", parent: "79", name: "eCommerce" },
        { key: "112", parent: "79", name: "ria"},
        { key: "113", parent: "79", name: "Webapps"},
        { key: "114", parent: "79", name: "microsoft" },
        { key: "115", parent: "43", name: "digitalMarketing" },
        { key: "116", parent: "43", name: "ecms"},
        { key: "117", parent: "43", name: "Gamification" },
        { key: "118", parent: "14", name: "downloads" },
        { key: "89", parent: "14", name: "view" }
        // { key: "90", parent: "43", name: "Azure" },
        // { key: "91", parent: "88", name: "GoogleAppEngine"},
        // { key: "92", parent: "88", name: "privatecloud"},
        // { key: "93", parent: "88", name: "salesforce"},
        // { key: "94", parent: "73", name: "ia" },
        // { key: "95", parent: "73", name: "portfolio"},
        // { key: "96", parent: "73", name: "rwd" },
        // { key: "98", parent: "73", name: "uxd"},
        // { key: "99", parent: "75", name: "iphone" },
        // { key: "100", parent: "75", name: "android"},
        // { key: "101", parent: "75", name: "crossplatform" },
        // { key: "102", parent: "75", name: "pwa"},
        // { key: "103", parent: "75", name: "windows"},
        // { key: "104", parent: "76", name: "competitive" },
        // { key: "105", parent: "76", name: "socialMedia" },
        // { key: "106", parent: "78", name: "performance"},
        // { key: "107", parent: "78", name: "security" },
        // { key: "108", parent: "72", name: "cloudSoln" }
        
    ];
    myDiagram.model = model;
}